/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{ts,tsx,js,jsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        error: '#ba1a1a',
        'on-surface': '#0b1c30',
        'on-primary-container': '#90a8ff',
        'error-container': '#ffdad6',
        'tertiary-fixed': '#ffddb8',
        'surface-container': '#e5eeff',
        'secondary-fixed': '#85f8c4',
        'on-primary-fixed-variant': '#264191',
        'on-primary-fixed': '#00164e',
        'on-surface-variant': '#444651',
        'outline-variant': '#c5c5d3',
        'tertiary-container': '#5c3800',
        secondary: '#006c4a',
        'on-secondary-fixed-variant': '#005137',
        'inverse-primary': '#b6c4ff',
        'on-secondary-fixed': '#002114',
        'inverse-on-surface': '#eaf1ff',
        surface: '#f8f9ff',
        background: '#f8f9ff',
        'on-secondary-container': '#00714e',
        'surface-dim': '#cbdbf5',
        'on-tertiary': '#ffffff',
        'tertiary-fixed-dim': '#ffb95f',
        'surface-container-low': '#eff4ff',
        outline: '#757682',
        'surface-variant': '#d3e4fe',
        'on-tertiary-fixed-variant': '#653e00',
        'on-tertiary-container': '#ef9900',
        'on-tertiary-fixed': '#2a1700',
        'on-error-container': '#93000a',
        'inverse-surface': '#213145',
        'surface-tint': '#4059aa',
        'primary-fixed': '#dce1ff',
        'primary-fixed-dim': '#b6c4ff',
        primary: '#00236f',
        'on-secondary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed-dim': '#68dba9',
        'on-background': '#0b1c30',
        tertiary: '#3e2400',
        'primary-container': '#1e3a8a',
        'secondary-container': '#82f5c1',
        'surface-container-highest': '#d3e4fe',
        'surface-bright': '#f8f9ff',
        'on-error': '#ffffff',
        'surface-container-high': '#dce9ff',
        'on-primary': '#ffffff',
      },
      borderRadius: { DEFAULT: '0.25rem', lg: '0.5rem', xl: '0.75rem', full: '9999px' },
      spacing: { 'space-xl': '2.5rem', 'margin-mobile': '1rem', 'space-sm': '0.5rem', 'space-md': '1rem', gutter: '1.5rem', 'space-xs': '0.25rem', margin: '2rem', 'space-lg': '1.5rem', 'gutter-mobile': '1rem' },
      fontFamily: {
        'headline-sm': ['Plus Jakarta Sans'],
        'display-lg': ['Plus Jakarta Sans'],
        'label-md': ['Be Vietnam Pro'],
        'headline-lg-mobile': ['Plus Jakarta Sans'],
        'headline-lg': ['Plus Jakarta Sans'],
        'title-md': ['Be Vietnam Pro'],
        'display-lg-mobile': ['Plus Jakarta Sans'],
        caption: ['Be Vietnam Pro'],
        'body-md': ['Be Vietnam Pro'],
        'label-sm': ['Be Vietnam Pro'],
        'body-lg': ['Be Vietnam Pro'],
        'body-sm': ['Be Vietnam Pro'],
        'headline-md': ['Plus Jakarta Sans'],
      },
      fontSize: {
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: 600 }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: 800 }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: 600 }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: 700 }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.015em', fontWeight: 700 }],
        'title-md': ['16px', { lineHeight: '24px', fontWeight: 600 }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: 800 }],
        caption: ['11px', { lineHeight: '14px', fontWeight: 500 }],
        'body-md': ['15px', { lineHeight: '24px', fontWeight: 400 }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: 600 }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: 400 }],
        'body-sm': ['13px', { lineHeight: '20px', fontWeight: 400 }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: 600 }],
      },
    },
  },
  plugins: [],
};
